### ISSUE TITLE
project - add READ for ipfsHash

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/radicle-drips#17]
I'm sure we'll add ipfsHash into the graph but probably should have a read method for ipfsHash no? (or is it elsewhere?)

**Comment by CodeSandwich** [comment]
An IPFS hash can be already read: https://github.com/radicle-dev/funding-contracts/blob/master/src/nft.sol#L32. It's a `public` contract variable, which means that the compiler automatically generates for it `function contractURI() public view returns(string) { return contractURI; }`. Does it cover our needs or do you mean something else?
